---
extends: airbnb-base

plugins: []

parser: babel-eslint

parserOptions: { }

env:
  browser: true
  node: true

globals:
  _: false
  _s: false
  page: false
  phina: true
  PIXI: true
  request: true
  yasu: true
  config: true
  app: true
  aoba: true
  hideaki: true
  mediator: true
  NODE_ENV: true

rules:
  arrow-body-style: 1
  space-infix-ops:
    - 0
    - int32Hint: true
  key-spacing:
    - error
    - mode: minimum
  brace-style:
    - 2
    - stroustrup
    - allowSingleLine: true
  comma-dangle: 0
  func-names: 0
  global-require: 0
  object-curly-spacing:
    - 0
    - always
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/newline-after-import: 0
  max-len:
    - 2
    - code: 120
  new-cap: 0
  no-console: 0
  no-continue: 0
  no-extra-semi: 0
  no-extra-boolean-cast: 0
  no-multi-spaces: 0
  no-underscore-dangle: 0
  no-unused-expressions:
    - 2
    - allowShortCircuit: true
  no-unused-vars:
    - 2
    - vars: all
      args: none
  no-useless-constructor: 0
  no-param-reassign: 0
  no-mixed-operators: 0
  no-var: 0
  object-shorthand: 0
  one-var-declaration-per-line: 0
  prefer-arrow-callback: 0
  prefer-rest-params: 0
  quote-props: 0
  spaced-comment: 0
  space-before-function-paren:
    - 2
    - never
  vars-on-top: 0
